server:
  port: 8082

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: modulo-auth
              uri: lb://MS-AUTH
              predicates:
                - Path=/auth/**
                
            - id: modulo-usuarios
              uri: lb://MS-USUARIOS
              predicates:
                - Path=/usuarios/**
                
            - id: modulo-roles
              uri: lb://MS-ROLES
              predicates:
                - Path=/roles/**
                
            - id: modulo-examenes
              uri: lb://MS-EXAMENES
              predicates:
                - Path=/examenes/**, /intentos/**, /categorias/**, /preguntas/**
                
            - id: modulo-incidencias
              uri: lb://MS-INCIDENCIAS
              predicates:
                - Path=/incidencias/**

eureka:
  client:
    serviceUrl:
      # Usa el nombre del contenedor de eureka, no localhost
      defaultZone: http://eureka:8761/eureka/