spring.application.name=examen-backend
spring.datasource.url=jdbc:mysql://localhost:3306/examenes
spring.datasource.username=root
spring.datasource.password=$$$$

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.security.user.name=user
spring.security.user.password=aplicacionDe_Examenes21100

#BASE_64_CODE
jwt.secret=RW1pbHkteS1NYXJ0aGEtdmVyZGFkZXJvLWFtb3ItcHVyby1hbW9y