version: '3.8'

services:
  db:
    image: mysql:8.0.33
    container_name: examen_mysql
    restart: always
    environment:
      MYSQL_DATABASE: examenes
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: eduardo
      MYSQL_PASSWORD: eduardopassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  eureka:
    build: ../eureka-server
    container_name: examen_eureka
    restart: on-failure
    ports:
      - "8761:8761"

  gateway:
    build: ../api-gateway
    container_name: examen_gateway
    restart: on-failure
    ports:
      - "8082:8082"
    depends_on:
      - eureka

  ms-auth:
    build: ../ms-auth # Asegúrate de que esta carpeta exista con su Dockerfile
    container_name: ms_auth
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
      eureka:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/examenes?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=eduardo
      - SPRING_DATASOURCE_PASSWORD=eduardopassword
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - SPRING_APPLICATION_NAME=MS-AUTH

  ms-usuarios:
    build: ../ms-usuarios
    container_name: ms_usuarios
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
      eureka:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/examenes?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=eduardo
      - SPRING_DATASOURCE_PASSWORD=eduardopassword
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - SPRING_APPLICATION_NAME=MS-USUARIOS

  ms-roles:
    build: ../ms-roles
    container_name: ms_roles
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
      eureka:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/examenes?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=eduardo
      - SPRING_DATASOURCE_PASSWORD=eduardopassword
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - SPRING_APPLICATION_NAME=MS-ROLES

  ms-examenes:
    build: ../ms-examenes
    container_name: ms_examenes
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
      eureka:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/examenes?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=eduardo
      - SPRING_DATASOURCE_PASSWORD=eduardopassword
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - SPRING_APPLICATION_NAME=MS-EXAMENES

  ms-incidencias:
    build: ../ms-incidencias
    container_name: ms_incidencias
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
      eureka:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/examenes?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=eduardo
      - SPRING_DATASOURCE_PASSWORD=eduardopassword
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - SPRING_APPLICATION_NAME=MS-INCIDENCIAS

volumes:
  mysql_data: